In [2]:
import numpy as np 

B = np.array([10.2,-12,20.1])
B
print(B.shape)

(3,)


In [3]:
B*2

array([ 20.4, -24. ,  40.2])

In [4]:
T=(10.5,-10,12,12+2j)
np.array(T)


array([ 10.5+0.j, -10. +0.j,  12. +0.j,  12. +2.j])

In [5]:
T =(10 , -20 , 15.5 , 5+2j)
B = np.array(T)
print(T)
print(B)
print(T*3)
print(B*3)

(10, -20, 15.5, (5+2j))
[ 10. +0.j -20. +0.j  15.5+0.j   5. +2.j]
(10, -20, 15.5, (5+2j), 10, -20, 15.5, (5+2j), 10, -20, 15.5, (5+2j))
[ 30. +0.j -60. +0.j  46.5+0.j  15. +6.j]


In [3]:
import numpy as np
A=np.arange(10)
B=np.arange(20,30)-10
C=np.arange(3,10)
print(A ,"       " ,B ,"      " ,C )
print(len(A))
print(len(B))
print(len(C))
print("=============================")
print(A.size)
print(B.size)
print(C.size)

[0 1 2 3 4 5 6 7 8 9]         [10 11 12 13 14 15 16 17 18 19]        [3 4 5 6 7 8 9]
10
10
7
10
10
7


In [7]:
np.arange(10,21,5)


array([10, 15, 20])

In [8]:
np.arange(20 ,step=5)

array([ 0,  5, 10, 15])

In [9]:
np.linspace(5,10,9)

array([ 5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   ])

In [10]:
A= np.linspace(5,15,9 ,retstep=True)
print(A)
print(A[0])
print(A[1])

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)
[ 5.    6.25  7.5   8.75 10.   11.25 12.5  13.75 15.  ]
1.25


In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.ones((3,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.zeros((11),dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
L=[2,-4,6,-8,10,20]
A=np.array(L)
B=np.array(A[0])
C=np.array(A[-1])
D=np.array(A[-3])
F=np.array(A[0:5])
G=np.array(A[2:])
print(A)
print(B)
print(C)
print(D)
print(F)
print(G)
print(A[0])
print(A[4])
print(A[5])
print(A[30%10])
print(A[35%10])
print(len(A))
print(A.size)
print(30%A.size)

[ 2 -4  6 -8 10 20]
2
20
-8
[ 2 -4  6 -8 10]
[ 6 -8 10 20]
2
10
20
2
20
6
6
0


In [19]:
A=np.arange(35)
A.shape =(7,5)
print(A)
print(A[0])
print(A[-2])
print(A[5])
print(A[4,2])
print(A[1][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[0 1 2 3 4]
[25 26 27 28 29]
[25 26 27 28 29]
22
7


In [20]:
B=np.arange(70)
B.shape = (2,7,5)
print(B)
print(B[0])
print(A[1])
print(B[1,2])
print(B[0,1,3])
B[0,1,3] = 10
print(B)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[5 6 7 8 9]
[45 46 47 48 49]
8
[[[ 0  1  2  3  4]
  [ 5  6  7 10  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [21]:
X=[4,8,5,1,10]
A=np.array(X)
print(A)


[ 4  8  5  1 10]


In [22]:
ZB = 0 ==(A%2)
print(ZB)

[ True  True False False  True]
