In [4]:
import numpy as np
k = np.array(np.arange(24).reshape(8,3))

print(k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [3]:
import numpy as np
A = np.array(np.arange(24))

print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
B= A.reshape(3,8)
print(B)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [12]:
C = A.reshape((2,3,4))
print(C)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# Flip left and right

In [17]:
print(np.fliplr(C))  # must 2_dimentional Arr
print("============================")
print(np.fliplr(B))   

[[[ 8  9 10 11]
  [ 4  5  6  7]
  [ 0  1  2  3]]

 [[20 21 22 23]
  [16 17 18 19]
  [12 13 14 15]]]
[[ 7  6  5  4  3  2  1  0]
 [15 14 13 12 11 10  9  8]
 [23 22 21 20 19 18 17 16]]


# Flip Up and down

In [20]:
print(np.flipud(C))  # must 2_dimentional Arr
print("============================")
print(np.flipud(B))  # must 2_dimentional Arr

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]


# Roll arry

In [54]:
print(np.roll(A,5))   # use at any dimentional +   take pos or negt prameter 
print("=================================================")
print(np.roll(A,-5))   # use at any dimentional -     take pos or negt prameter 
print("=================================================")
print(np.roll(B,2))     # use at any dimentional +    take pos or negt prameter 
print("=================================================")
print(np.roll(B,-2))   # use at any dimentional -    take pos or negt prameter 
print("=================================================")
print(np.roll(C,2))    # use at any dimentional +    take pos or negt prameter 
print("=================================================")
print(np.roll(C,-2))   # use at any dimentional-    take pos or negt prameter 
print("=================================================")
print(np.rollaxis(C,0,2))
print("=================================================")
print(np.rollaxis(C,1,1))
print("=================================================")
print(np.rollaxis(C,2,0))

[19 20 21 22 23  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23  0  1  2  3  4]
[[22 23  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23  0  1]]
[[[22 23  0  1]
  [ 2  3  4  5]
  [ 6  7  8  9]]

 [[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]]
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23  0  1]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


# Rotate arr

In [28]:
print(B)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [31]:
print(np.rot90(B))  #Rot by 90

[[ 7 15 23]
 [ 6 14 22]
 [ 5 13 21]
 [ 4 12 20]
 [ 3 11 19]
 [ 2 10 18]
 [ 1  9 17]
 [ 0  8 16]]


In [32]:
print(np.rot90(B, k=-1))  # Rot by -90

[[16  8  0]
 [17  9  1]
 [18 10  2]
 [19 11  3]
 [20 12  4]
 [21 13  5]
 [22 14  6]
 [23 15  7]]


In [ ]:
print(np.rollaxes())

# Transpose Fun arr

In [38]:
print(np.transpose(A))  # 1_dimentional
print("==============================================")
#print(np.transpose( B , axes = (0,2,1)))  # 2_dimentional Error
print("==============================================")
print(np.transpose( C , axes = (0,2,1)))  # 2_dimentional

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


# Swapaxes fun

In [52]:
print(np.swapaxes(B,1,0))  # for column
print("==============================================")
print(np.swapaxes(B,0,1))  # for column
print("==============================================")
print(np.swapaxes(B,0,0))  # for rows
print("==============================================")
print(np.swapaxes(B,1,1))  #for rows
print("==============================================")
print(np.swapaxes(C,1,0))  # for colums
print("==============================================")
print(np.swapaxes(C,1,1))  # for rows
print("==============================================")
print(np.swapaxes(A,0,0))
print("==============================================")
#print(np.swapaxes(A,1,0))  # have 1_dimentional

[[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]
[[ 0  8 16]
 [ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Till Fun arr

In [55]:
W = np.array(np.arange(12))
print(W)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [67]:
print(np.tile(W,4))
print("===============================================================")
print(np.tile(W,3))
print("===============================================================")
print(np.tile(W,3).reshape(3,12))
print("===============================================================")
print(np.tile(W,4).reshape(4,12))




[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11
  0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11
  0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [74]:
Z = np.array(np.arange(7))
print(Z)
print("===============================================================")
T1=np.tile(Z,(3,1))
print(T1)
print("===============================================================")
T2 = np.tile(T1,(2,2))
print(T2)
print("===============================================================")
T3 = np.tile(T2,(3,3))
print(T3)

[0 1 2 3 4 5 6]
[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
[[0 1 2 3 4 5 6 0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6]]
[[0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
  1 2 3 4 5 6]
 [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1

# REPEAT FUN ARR

In [76]:
print(Z)

[0 1 2 3 4 5 6]


# 1_dimentional repeat

In [77]:
print(np.repeat(Z,2))
print("===============================================================")
print(np.repeat(Z,3))

[0 0 1 1 2 2 3 3 4 4 5 5 6 6]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


# 2_dimentional repeat

In [78]:
print(C)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [82]:
print(np.repeat(C,2,axis=0))  # axis = 0  for rows and Columns repeat    and 2 num of repeat
print("===============================================================")
print(np.repeat(C,3,axis=0))  # axis = 0  for rows and Columns repeat    and 3 num of repeat

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [84]:
print(np.repeat(C,2,axis=1))  # axis =1 for Rows only   and  2  num of repeat
print("===============================================================")
print(np.repeat(C,3,axis=1))   # axis =1 for Rows only   and  3  num of repeat

[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]
  [16 17 18 19]
  [16 17 18 19]
  [20 21 22 23]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]
  [12 13 14 15]
  [16 17 18 19]
  [16 17 18 19]
  [16 17 18 19]
  [20 21 22 23]
  [20 21 22 23]
  [20 21 22 23]]]


In [85]:
print(np.repeat(C,2,axis=2))  # axis =2 for Columns only   and  2  num of repeat
print("===============================================================")
print(np.repeat(C,3,axis=2))   # axis =2 for Columns only   and  3  num of repeat

[[[ 0  0  1  1  2  2  3  3]
  [ 4  4  5  5  6  6  7  7]
  [ 8  8  9  9 10 10 11 11]]

 [[12 12 13 13 14 14 15 15]
  [16 16 17 17 18 18 19 19]
  [20 20 21 21 22 22 23 23]]]
[[[ 0  0  0  1  1  1  2  2  2  3  3  3]
  [ 4  4  4  5  5  5  6  6  6  7  7  7]
  [ 8  8  8  9  9  9 10 10 10 11 11 11]]

 [[12 12 12 13 13 13 14 14 14 15 15 15]
  [16 16 16 17 17 17 18 18 18 19 19 19]
  [20 20 20 21 21 21 22 22 22 23 23 23]]]
