# Addition

In [3]:
import numpy as np
A = np.arange(24).reshape(2,3,4)
print(A)
print("=================================")
print(A.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [5]:
B = np.append(A,[11,22,33,44])
print(B)
print("=================================")

print(B.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 11 22 33 44]
(28,)


In [8]:
print(B.reshape(7,4))

print("=================================")
print(A)
print("=================================")
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [11 22 33 44]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 11 22 33 44]


In [26]:
C = np.array(np.arange(24).reshape(2,3,4) * 10+3)
print(C)
print("=================================")
print(C.shape)
print("=================================")
print(C.size)
print("=================================")
print(C.dtype)
print("=================================")
print(type(C))
print("=================================")
print(C.ndim)

[[[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]
(2, 3, 4)
24
int32
<class 'numpy.ndarray'>
3


In [28]:
print(np.append(A,C,axis=0))
print("=================================")

print(np.append(A,C,axis=0).shape)


[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]

 [[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]
(4, 3, 4)


In [30]:
print(np.append(A,C,axis=1))
print("=================================")
print(np.append(A,C,axis=1).shape)




[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]
  [123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]
(2, 6, 4)


In [31]:
print(np.append(A,C,axis=2))
print("=================================")
print(np.append(A,C,axis=2).shape)



[[[  0   1   2   3   3  13  23  33]
  [  4   5   6   7  43  53  63  73]
  [  8   9  10  11  83  93 103 113]]

 [[ 12  13  14  15 123 133 143 153]
  [ 16  17  18  19 163 173 183 193]
  [ 20  21  22  23 203 213 223 233]]]
(2, 3, 8)


# Herezontal_Stack

In [34]:
Her_stack = np.hstack((A,C))
print(Her_stack)
print("=================================")
print(Her_stack.shape)
print("=================================")
print(Her_stack.size)
print("=================================")
print(Her_stack.dtype)



[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]
  [123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]
(2, 6, 4)
48
int32


In [35]:
Her_stack[0,0,2] = 666
Her_stack[1,1,3] = 999
print(Her_stack)
print("=================================")
print(A)
print("=================================")
print(C)

[[[  0   1 666   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[ 12  13  14  15]
  [ 16  17  18 999]
  [ 20  21  22  23]
  [123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]


# Insert Operation

In [37]:
I = np.insert(C,1,444,axis=0)
print(I)

[[[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[444 444 444 444]
  [444 444 444 444]
  [444 444 444 444]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]


In [45]:
print(np.insert(C,1,333,axis =1))  # axis = 1 change rows    and 1  index
print("=================================")
print(np.insert(C,1,111,axis=2))   # axis = 2 change coums    and 1  index
print("=================================")
print(np.insert(C,2,555,axis=1))   # axis = 1 change rows     and 2  index
print("=================================")
print(np.insert(C,2,777,axis=2))    # axis = 2 change coums   and 2  index

[[[  3  13  23  33]
  [333 333 333 333]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [333 333 333 333]
  [163 173 183 193]
  [203 213 223 233]]]
[[[  3 111  13  23  33]
  [ 43 111  53  63  73]
  [ 83 111  93 103 113]]

 [[123 111 133 143 153]
  [163 111 173 183 193]
  [203 111 213 223 233]]]
[[[  3  13  23  33]
  [ 43  53  63  73]
  [555 555 555 555]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [555 555 555 555]
  [203 213 223 233]]]
[[[  3  13 777  23  33]
  [ 43  53 777  63  73]
  [ 83  93 777 103 113]]

 [[123 133 777 143 153]
  [163 173 777 183 193]
  [203 213 777 223 233]]]


# Create empty Arry Shepe  as anouther Arry

In [50]:
W = np.empty(C.shape)  # create empty array has shape of C
np.copyto(W,C)  # Copy Array C in Empty array W
print(W)
print("=================================")
print(W.shape)
print("=================================")
print(W.size)
print("=================================")
print(W.ndim)
print("=================================")
print(W.itemsize)
print("=================================")
print(len(W))  # let to number of Dimentional 


[[[  3.  13.  23.  33.]
  [ 43.  53.  63.  73.]
  [ 83.  93. 103. 113.]]

 [[123. 133. 143. 153.]
  [163. 173. 183. 193.]
  [203. 213. 223. 233.]]]
(2, 3, 4)
24
3
8
2


# Delet Operation

# 1 _ delet dimentional

In [53]:
print(np.delete ( W , 0 , axis = 0)) # 0 index of dimentiona ,, axis = 0 >>delet rows and columns
print(np.delete ( W , 1 , axis = 0)) # 1 index of dimentiona ,, axis = 0 >>delet rows and columns

[[[123. 133. 143. 153.]
  [163. 173. 183. 193.]
  [203. 213. 223. 233.]]]


 # 2 _ delet Rows only 

In [56]:
print(np.delete ( W , 0 , axis = 1)) # 0 let to index of delet  ,, axis =1  delet Rows only 
print("=================================")
print(np.delete ( W , 1 , axis = 1)) # 1 let to index of delet  ,, axis =1  delet Rows only 


[[[ 43.  53.  63.  73.]
  [ 83.  93. 103. 113.]]

 [[163. 173. 183. 193.]
  [203. 213. 223. 233.]]]
[[[  3.  13.  23.  33.]
  [ 83.  93. 103. 113.]]

 [[123. 133. 143. 153.]
  [203. 213. 223. 233.]]]


 # 3 _ delet Columns only

In [58]:
print(np.delete ( W , 1 , axis = 2 ))  # 1 let to index of delet  ,, axis =2  delet Colums only 
print("=================================")
print(np.delete ( W , 2 , axis = 2 ))  # 2 let to index of delet  ,, axis =2  delet Colums onl

[[[  3.  23.  33.]
  [ 43.  63.  73.]
  [ 83. 103. 113.]]

 [[123. 143. 153.]
  [163. 183. 193.]
  [203. 223. 233.]]]
[[[  3.  13.  33.]
  [ 43.  53.  73.]
  [ 83.  93. 113.]]

 [[123. 133. 153.]
  [163. 173. 193.]
  [203. 213. 233.]]]
