# Structure Array

# 1_dimentional

In [42]:
import numpy as np
Data_Structure_def = [('name','S6') ,('weight','f8') ,('height','f8') ,('adge','i8')]
print(Data_Structure_def)


[('name', 'S6'), ('weight', 'f8'), ('height', 'f8'), ('adge', 'i8')]


In [43]:
A = np.zeros((4),dtype=Data_Structure_def)
print(A)

[(b'', 0., 0., 0) (b'', 0., 0., 0) (b'', 0., 0., 0) (b'', 0., 0., 0)]


In [50]:
A[1] = ("Ahmed",70,100,34)
A[3] = ("Mido",120,100,55)
print(A)
print("=================================")
print(A[0:])
print("=================================")
Adges = A["adge"]
print(Adges)
print("=================================")
Names = A["name"]
print(Names)
print("=================================")
print(Adge/3)
print("=================================")
print(A)


[(b'',   0.,   0.,  0) (b'Ahmed',  70., 100., 34) (b'',   0.,   0.,  0)
 (b'Mido', 120., 100., 55)]
[(b'',   0.,   0.,  0) (b'Ahmed',  70., 100., 34) (b'',   0.,   0.,  0)
 (b'Mido', 120., 100., 55)]
[ 0 34  0 55]
[b'' b'Ahmed' b'' b'Mido']
[ 0.         11.33333333  0.         18.33333333]
[(b'',   0.,   0.,  0) (b'Ahmed',  70., 100., 34) (b'',   0.,   0.,  0)
 (b'Mido', 120., 100., 55)]


# Multi_dimentional array

In [55]:
B = np.zeros((4,3,2),dtype=Data_Structure_def)
print(B)

[[[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]]


In [62]:
B[1,1,0] = ("Ali",70,100,20)
B[2,1,1] = ("Taha",100,80,26)
B[3,0,0] = ("Ahmed",90,110,30)
print(B)
print("=================================")
Adge=B["adge"]
print(Adge)
print("=================================")
print(Adge//2)
print("=================================")
Height =B["height"]
print(Height)

[[[(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]]

 [[(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]
  [(b'Ali',  70., 100., 20) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]]

 [[(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'Taha', 100.,  80., 26)]
  [(b'',   0.,   0.,  0) (b'Taha', 100.,  80., 26)]]

 [[(b'Ahmed',  90., 110., 30) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]
  [(b'',   0.,   0.,  0) (b'',   0.,   0.,  0)]]]
[[[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [20  0]
  [ 0  0]]

 [[ 0  0]
  [ 0 26]
  [ 0 26]]

 [[30  0]
  [ 0  0]
  [ 0  0]]]
[[[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [10  0]
  [ 0  0]]

 [[ 0  0]
  [ 0 13]
  [ 0 13]]

 [[15  0]
  [ 0  0]
  [ 0  0]]]
[[[  0.   0.]
  [  0.   0.]
  [  0.   0.]]

 [[  0.   0.]
  [100.   0.]
  [  0.   0.]]

 [[  0.   0.]
  [  0.  80.]
  [  0.  80.]]

 [[110.   0.

# Array_Recording

In [70]:
R = np.rec.array([("Ahmed",70,100,34), ("Mido",120,100,55) ], dtype = Data_Structure_def) 
print(R)
print("===============")
print(R[0].adge)
print("===============")
print(R[1].name)
print("===============")
print(R[0].weight)
print("===============")
print(R[1].weight)

[(b'Ahmed',  70., 100., 34) (b'Mido', 120., 100., 55)]
34
b'Mido'
70.0
120.0


# Some Function In Numpy

In [1]:
import numpy as np
Z = np.arange(24).reshape(2,3,4)
print(Z)
print("=================================")
print(id(Z))
print("=================================")
print(Z.shape)
print("=================================")
print(Z.ndim)
print("=================================")
print(Z.size)
print("=================================")
print(Z.itemsize)
print("=================================")
print(len(Z))
print("=================================")
print(Z.dtype)
print("=================================")
print(type(Z))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
393583075776
(2, 3, 4)
3
24
4
2
int32
<class 'numpy.ndarray'>
