# Unniversal Fun

 # 1 Create Func Module

In [3]:
import numpy as np
def truncated_binomial (X) :
    return (X+1)**3 - (X)**3

# Error Func

In [9]:
#np.testing.assert_equal(truncated_binomial(4),61)
#np.testing.assert_equal(truncated_binomial(4),65)

 # 2 Create Func in Nupy

In [10]:
NP_Func = np.frompyfunc ( truncated_binomial , 1 , 1)
print(NP_Func)

<ufunc '? (vectorized)'>


 # 3 Create Arr And implementation Fun on it

In [11]:
T_Func = np.arange(10)
print(T_Func)
print("===========================")
print("===========================")
print(NP_Func(T_Func))

[0 1 2 3 4 5 6 7 8 9]
[1 7 19 37 61 91 127 169 217 271]


 # 4 Get Big Test Fun

In [13]:
B_T_Func = np.outer( T_Func , T_Func )
print(B_T_Func)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


 # 5 implementation Numpy Func On T_Func   and  On  B_T_Func 

In [15]:
print(NP_Func(T_Func))

print("===========================")
print("===========================")
print("===========================")

print(NP_Func(B_T_Func))

[1 7 19 37 61 91 127 169 217 271]
[[1 1 1 1 1 1 1 1 1 1]
 [1 7 19 37 61 91 127 169 217 271]
 [1 19 61 127 217 331 469 631 817 1027]
 [1 37 127 271 469 721 1027 1387 1801 2269]
 [1 61 217 469 817 1261 1801 2437 3169 3997]
 [1 91 331 721 1261 1951 2791 3781 4921 6211]
 [1 127 469 1027 1801 2791 3997 5419 7057 8911]
 [1 169 631 1387 2437 3781 5419 7351 9577 12097]
 [1 217 817 1801 3169 4921 7057 9577 12481 15769]
 [1 271 1027 2269 3997 6211 8911 12097 15769 19927]]


# Pythagorean Triplet

In [21]:
import numpy as np
def is_integer (X) :
    return np.equal(np.mod(X,1) , 0)

    
    

In [22]:
Np_Int = np.frompyfunc( is_integer , 1 , 1)

In [24]:
Num_Tringle = 9
Base = np.arange( Num_Tringle ) +1
Height = np.arange( Num_Tringle ) +1

Hyposes_sqr_func = np.add.outer( Base**2 , Height**2)
Hyposes_T = np.sqrt(Hyposes_sqr_func)
print(Np_Int(Hyposes_T))



[[False False False False False False False False False]
 [False False False False False False False False False]
 [False False False True False False False False False]
 [False False True False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False True False]
 [False False False False False False False False False]
 [False False False False False True False False False]
 [False False False False False False False False False]]
