# Compare Btween Arrays

In [2]:
import numpy as np
A = np.array()
print(A)
print("=================================")
print(id(A))

[ 10  15 -12  80  33   7]
117204793584


In [3]:
B=A
print(B)
print("=================================")
print(id(B))

[ 10  15 -12  80  33   7]
117204793584


In [4]:
A is B

True

In [5]:
A==B

array([ True,  True,  True,  True,  True,  True])

In [7]:
A[0] = 20
A[2] = 12
print(A)
print("=================================")
print(B)
print("=================================")
print(id(A))
print("=================================")
print(id(B))

[20 15 12 80 33  7]
[20 15 12 80 33  7]
117204793584
117204793584


In [23]:
C = np.array([10,15,-12,80,33,7])
print(C)
print("=================================")
print(id(C))
print("=================================")
print(A)
print("=================================")

print(id(A))

print("=================================")

C is A





[ 10  15 -12  80  33   7]
117165217552
[ 20  15 200  80 100   7]
117204793584


False

In [24]:
C[4]=100
C[2]=200
print(C)


[ 10  15 200  80 100   7]


In [25]:
C is B

False

In [26]:
C is A

False

In [31]:
print(C == B)
print("=================================")

print(C == A)
print("=================================")

print(id(C))
print("=================================")

print(id(A))
print("=================================")

print(id(B))

[False  True  True  True  True  True]
[False  True  True  True  True  True]
117165217552
117204793584
117204793584


# View : Show Copy

In [35]:
F = C.view()
print(C)
print("=================================")
print(id(C))
print("=================================")
print(F)
print("=================================")

print(F.reshape(2,3))
print("=================================")
print(id(F))

print("=================================")
print(F is C)
print("=================================")
print(F == C)

[ 10  15 200  80 100   7]
117165217552
[ 10  15 200  80 100   7]
[[ 10  15 200]
 [ 80 100   7]]
117165218352
False
[ True  True  True  True  True  True]


In [37]:
F[0]=11
print(F)
print("=================================")
print(C)

[ 11  15 200  80 100   7]
[ 11  15 200  80 100   7]


# Deep Copy

In [40]:
 W = np.copy(C)
W[0]=121
print(C)
print("=================================")
print(W)
print("=================================")
print(id(C))
print("=================================")
print(id(W))
print("=================================")

print(W is C)
print("=================================")
print(W == C)


[ 11  15 200  80 100   7]
[121  15 200  80 100   7]
117165217552
117165253456
False
[False  True  True  True  True  True]
