In [ ]:
# from liberary import modules and classs

from sklearn.impute import SimpleImputer
#import numpy liberary
import numpy as np

#The Attr ond its parameters of classs

""" impute.SimpleImputer(missing_values=nan, strategy='Mean , Median , Mod , Constan’,
fill_value=None, verbose=0, copy=True)"""

# create object from class

Simplel_impute = SimpleImputer(missing_values = np.nan , strategy="mean")

# define variable to fit data

Impute_data = Simplel_impute.fit(data)

# get the new_data after filling missing values , or any values to chance

data = Impute_data.transform(data)

# Example 1

In [3]:
from sklearn.impute import SimpleImputer
data = [[0 , 2 , 3] ,
        [4 , 0 , 6] ,
        [7 , 8 , 0] ,
        [10 , 0 , 0]]

Impute_data = SimpleImputer( missing_values = 0 , strategy = "mean")

Impute_data = Impute_data.fit(data)
data = Impute_data.transform(data)

In [4]:
data

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  4.5],
       [10. ,  5. ,  4.5]])

In [6]:
from sklearn.impute import SimpleImputer
data = [[0 , 2 , 3] ,
        [4 , 0 , 6] ,
        [7 , 8 , 0] ,
        [10 , 0 , 0]]

Impute_data = SimpleImputer( missing_values = 0 , strategy = "mean").fit(data)
data = Impute_data.transform(data)
data

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  4.5],
       [10. ,  5. ,  4.5]])

In [10]:
from sklearn.impute import SimpleImputer
data1 = [[0 , 2 , 3 , 2] ,
        [4 , 0 , 6 , 4] ,
        [7 , 8 , 0 , 7] ,
        [10 , 0 , 0 , 10]]

Impute_data1 = SimpleImputer( missing_values = 0 , strategy = "median").fit(data1)
data1 = Impute_data1.transform(data1)
data1

array([[ 7. ,  2. ,  3. ,  2. ],
       [ 4. ,  5. ,  6. ,  4. ],
       [ 7. ,  8. ,  4.5,  7. ],
       [10. ,  5. ,  4.5, 10. ]])

In [13]:
from sklearn.impute import SimpleImputer
data2 = [[0 , 2 , 3 , 2] ,
        [4 , 0 , 6 , 4] ,
        [7 , 8 , 0 , 7] ,
        [10 , 0 , 0 , 10]]

Impute_data2 = SimpleImputer( missing_values = 0 , strategy = "most_frequent").fit(data2)
data2 = Impute_data2.transform(data2)
data2

array([[ 4,  2,  3,  2],
       [ 4,  2,  6,  4],
       [ 7,  8,  3,  7],
       [10,  2,  3, 10]])

In [14]:
from sklearn.impute import SimpleImputer
data3 = [[0 , 2 , 3 , 2] ,
        [4 , 0 , 6 , 4] ,
        [7 , 8 , 0 , 7] ,
        [10 , 0 , 0 , 10]]

Impute_data3 = SimpleImputer( missing_values = 0 , strategy = "constant").fit(data3)
data3 = Impute_data3.transform(data3)
data3

array([[ 0,  2,  3,  2],
       [ 4,  0,  6,  4],
       [ 7,  8,  0,  7],
       [10,  0,  0, 10]])

In [15]:
from sklearn.impute import SimpleImputer
import numpy as np
data4 = [[np.nan , 2 , 3 , 2] ,
        [4 , np.nan , 6 , 4] ,
        [7 , 8 , np.nan , 7] ,
        [10 , np.nan , np.nan , 10]]

Impute_data4 = SimpleImputer( missing_values = np.nan , strategy = "mean").fit(data4)
data4 = Impute_data4.transform(data4)
data4

array([[ 7. ,  2. ,  3. ,  2. ],
       [ 4. ,  5. ,  6. ,  4. ],
       [ 7. ,  8. ,  4.5,  7. ],
       [10. ,  5. ,  4.5, 10. ]])