 # Precision recall f_score Support

In [2]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
y_true =  np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])

#Calculating Precision recall Score :  
#metrics.precision_recall_fscore_support(y_true, y_pred, beta=1.0, labels=None, pos_label=1, average=
# None, warn_for = ('precision’,’recall’, ’f-score’), sample_weight=None)

PRFS = precision_recall_fscore_support(y_pred , y_true , average=None)
PRFS  #return [ precision ,  recall , fscore , support ]

(array([1., 0., 0.]),
 array([0.66666667, 0.        , 0.        ]),
 array([0.8, 0. , 0. ]),
 array([3, 2, 1], dtype=int64))

In [3]:
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
y_true =  np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])

#Calculating Precision recall Score :  
#metrics.precision_recall_fscore_support(y_true, y_pred, beta=1.0, labels=None, pos_label=1, average=
# None, warn_for = ('precision’,’recall’, ’f-score’), sample_weight=None)

PRFS = precision_recall_fscore_support(y_pred , y_true , average="micro")
PRFS  #return [ precision ,  recall , fscore , support ]

(0.3333333333333333, 0.3333333333333333, 0.3333333333333333, None)

# precision recall curve

In [5]:
from sklearn.metrics import precision_recall_curve
import numpy as np

y_pred =  np.array([0, 0, 1, 1])
y_true =   np.array([0.1, 0.4, 0.35, 0.8])



#Calculating Precision recall Curve :  
# precision_recall_curve(y_true, probas_pred, pos_label=None, sample_weight=None)

Precision , Recall , Threshold = precision_recall_curve(y_pred , y_true)  # return three values 

print(f"The Precision :: {Precision}\n===\nThe Recall :: {Recall}\n===\nThe Threshold :: {Threshold}")

The Precision :: [0.66666667 0.5        1.         1.        ]
===
The Recall :: [1.  0.5 0.5 0. ]
===
The Threshold :: [0.35 0.4  0.8 ]


 # classification Report 

     Most Use becoue talk less Time and Work

In [8]:
from sklearn.metrics import classification_report

y_true = [0, 1, 2, 2, 2,5]
y_pred = [0, 0, 2, 2, 1,0]

#Calculating classification Report :  
#classification_report(y_true, y_pred, labels=None, 
#target_names=None,sample_weight=None, digits=2, output_dict=False)


Clasifier_Report = classification_report(y_pred , y_true)
print(Clasifier_Report)  # return alues of ( Precision , Recall , Fscore , support , .....)

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         3
           1       0.00      0.00      0.00         1
           2       0.67      1.00      0.80         2
           5       0.00      0.00      0.00         0

    accuracy                           0.50         6
   macro avg       0.42      0.33      0.33         6
weighted avg       0.72      0.50      0.52         6



In [9]:
from sklearn.metrics import classification_report

y_true = ['a','d','a','g','a','d']
y_pred = ['a','a','g','g','d','g']

#Calculating classification Report :  
#classification_report(y_true, y_pred, labels=None, 
#target_names=None,sample_weight=None, digits=2, output_dict=False)


Clasifier_Report = classification_report(y_pred , y_true)
print(Clasifier_Report)  # return alues of ( Precision , Recall , Fscore , support , .....)

              precision    recall  f1-score   support

           a       0.33      0.50      0.40         2
           d       0.00      0.00      0.00         1
           g       1.00      0.33      0.50         3

    accuracy                           0.33         6
   macro avg       0.44      0.28      0.30         6
weighted avg       0.61      0.33      0.38         6



# Roc Curve

     Most use in Binary classification

In [12]:
from sklearn.metrics import roc_curve

y =      np.array([1    , 1     , 2     , 2])
scores = np.array([0.1  , 0.4   ,   0.35, 0.8])

#Calculating Receiver Operating Characteristic :  
#roc_curve(y_true, y_score, pos_label=None, sample_weight=None,drop_intermediate=True)


FPS , TPS , Thrshold = roc_curve(y , scores , pos_label=2)
print(f"The False Positive Rate :: {FPS}\n===\nThe True Positive Rate :: {TPS}\n===\n\
The Threshold :: {Thrshold}") # return three Values

The False Positive Rate :: [0.  0.  0.5 0.5 1. ]
===
The True Positive Rate :: [0.  0.5 0.5 1.  1. ]
===
The Threshold :: [1.8  0.8  0.4  0.35 0.1 ]
