# K_Fold

In [ ]:
#Import Libraries
from sklearn.model_selection import KFold
#----------------------------------------------------

#KFold Splitting data

kf = KFold(n_splits=4, random_state=44, shuffle =True)

#KFold Data
for train_index, test_index in kf.split(X):
    print('Train Data is : \n', train_index)
    print('Test Data is  : \n', test_index)
    print('-------------------------------')
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train Shape is  ' , X_train.shape)
    print('X_test Shape is  ' , X_test.shape)
    print('y_train Shape is  ' ,y_train.shape)
    print('y_test Shape is  ' , y_test.shape)
    print('========================================')

In [7]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

y = np.array([11, 22, 33, 44])


K_F = KFold( n_splits= 2 , random_state =40  , shuffle = True)

for train_index , test_index in K_F.split(X) :
    X_Train , X_Test = X[train_index] , X[test_index]
    y_Train , y_Test = y[train_index] , y[test_index]
    

    print(f"The X_data ::\n\n{X}\n===\nThe y_data ::\n\n{y}\n===\nThe X_Train ::\n\n{X_Train}\n===\n\
The X_test :: \n\n{X_Test}\nThe Y_Train :: \n\n {y_Train}\nThe y_Test :: \n\n{y_Test}\n===\n\
The X_shap :: {X.shape}\n==\nThe y_shape :: {y.shape}\n==\nThe X_Train_shape :: {X_Train.shape}\n==\n\
The X_Test_shape :: {X_Test.shape}\n===\nThe y_Train_shape:: {y_Train.shape}\n==\nThe y_Test_Shape :: \
{y_Test.shape}\n===\nThe Train_Index :: {train_index}\n===\nThe Test_Index :: {test_index}\n\n**********\n")
    

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[11 22 33 44]
===
The X_Train ::

[[3 4]
 [5 6]]
===
The X_test :: 

[[1 2]
 [7 8]]
The Y_Train :: 

 [22 33]
The y_Test :: 

[11 44]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [1 2]
===
The Test_Index :: [0 3]

**********

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[11 22 33 44]
===
The X_Train ::

[[1 2]
 [7 8]]
===
The X_test :: 

[[3 4]
 [5 6]]
The Y_Train :: 

 [11 44]
The y_Test :: 

[22 33]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [0 3]
===
The Test_Index :: [1 2]

**********



In [4]:
K_F.get_n_splits(X)

2