# Leave P Out

    Choice custom number to Split data  into testing and training 

In [1]:
import numpy as np
from sklearn.model_selection import LeavePOut
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
#lpo = LeavePOut(1)
#lpo = LeavePOut(2)
lpo = LeavePOut(3)

lpo.get_n_splits(X)

print(lpo)
LeavePOut(p=2)
for train_index, test_index in lpo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


LeavePOut(p=3)
TRAIN: [3] TEST: [0 1 2]
X_train 
 [[7 8]]
X_test 
 [[1 2]
 [3 4]
 [5 6]]
y_train 
 [4]
y_test 
 [1 2 3]
*********************
TRAIN: [2] TEST: [0 1 3]
X_train 
 [[5 6]]
X_test 
 [[1 2]
 [3 4]
 [7 8]]
y_train 
 [3]
y_test 
 [1 2 4]
*********************
TRAIN: [1] TEST: [0 2 3]
X_train 
 [[3 4]]
X_test 
 [[1 2]
 [5 6]
 [7 8]]
y_train 
 [2]
y_test 
 [1 3 4]
*********************
TRAIN: [0] TEST: [1 2 3]
X_train 
 [[1 2]]
X_test 
 [[3 4]
 [5 6]
 [7 8]]
y_train 
 [1]
y_test 
 [2 3 4]
*********************


In [3]:
# import liberary

import numpy as np
from sklearn.model_selection import LeavePOut

#Data

X = np.array([1, 2, 3, 4])

y = np.array([5,6,7,8])

# Create Object from Class

L_P_O = LeavePOut(3)

splitation = L_P_O.get_n_splits(X)

# get X_tarin , X_text , y_train , y_test 

for train_index , test_index in L_P_O.split(X) :
    X_Train , X_Test = X[train_index] , X[test_index]
    y_Train , y_Test = y[train_index] , y[test_index]
    
    print(f"The X_data ::\n\n{X}\n===\nThe y_data ::\n\n{y}\n===\nThe X_Train ::\n\n{X_Train}\n===\n\
The X_test :: \n\n{X_Test}\nThe Y_Train :: \n\n {y_Train}\nThe y_Test :: \n\n{y_Test}\n===\n\
The X_shap :: {X.shape}\n==\nThe y_shape :: {y.shape}\n==\nThe X_Train_shape :: {X_Train.shape}\n==\n\
The X_Test_shape :: {X_Test.shape}\n===\nThe y_Train_shape:: {y_Train.shape}\n==\nThe y_Test_Shape :: \
{y_Test.shape}\n===\nThe Train_Index :: {train_index}\n===\nThe Test_Index :: {test_index}\n\n*********\n")
    

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[4]
===
The X_test :: 

[1 2 3]
The Y_Train :: 

 [8]
The y_Test :: 

[5 6 7]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (1,)
==
The X_Test_shape :: (3,)
===
The y_Train_shape:: (1,)
==
The y_Test_Shape :: (3,)
===
The Train_Index :: [3]
===
The Test_Index :: [0 1 2]

*********

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[3]
===
The X_test :: 

[1 2 4]
The Y_Train :: 

 [7]
The y_Test :: 

[5 6 8]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (1,)
==
The X_Test_shape :: (3,)
===
The y_Train_shape:: (1,)
==
The y_Test_Shape :: (3,)
===
The Train_Index :: [2]
===
The Test_Index :: [0 1 3]

*********

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[2]
===
The X_test :: 

[1 3 4]
The Y_Train :: 

 [6]
The y_Test :: 

[5 7 8]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (1,)
==
The X_Te

In [4]:
import numpy as np
from sklearn.model_selection import LeavePOut
X = np.ones(10)
lpo = LeavePOut(p=3)
for train, test in lpo.split(X):
    print("%s %s" % (train, test))


[3 4 5 6 7 8 9] [0 1 2]
[2 4 5 6 7 8 9] [0 1 3]
[2 3 5 6 7 8 9] [0 1 4]
[2 3 4 6 7 8 9] [0 1 5]
[2 3 4 5 7 8 9] [0 1 6]
[2 3 4 5 6 8 9] [0 1 7]
[2 3 4 5 6 7 9] [0 1 8]
[2 3 4 5 6 7 8] [0 1 9]
[1 4 5 6 7 8 9] [0 2 3]
[1 3 5 6 7 8 9] [0 2 4]
[1 3 4 6 7 8 9] [0 2 5]
[1 3 4 5 7 8 9] [0 2 6]
[1 3 4 5 6 8 9] [0 2 7]
[1 3 4 5 6 7 9] [0 2 8]
[1 3 4 5 6 7 8] [0 2 9]
[1 2 5 6 7 8 9] [0 3 4]
[1 2 4 6 7 8 9] [0 3 5]
[1 2 4 5 7 8 9] [0 3 6]
[1 2 4 5 6 8 9] [0 3 7]
[1 2 4 5 6 7 9] [0 3 8]
[1 2 4 5 6 7 8] [0 3 9]
[1 2 3 6 7 8 9] [0 4 5]
[1 2 3 5 7 8 9] [0 4 6]
[1 2 3 5 6 8 9] [0 4 7]
[1 2 3 5 6 7 9] [0 4 8]
[1 2 3 5 6 7 8] [0 4 9]
[1 2 3 4 7 8 9] [0 5 6]
[1 2 3 4 6 8 9] [0 5 7]
[1 2 3 4 6 7 9] [0 5 8]
[1 2 3 4 6 7 8] [0 5 9]
[1 2 3 4 5 8 9] [0 6 7]
[1 2 3 4 5 7 9] [0 6 8]
[1 2 3 4 5 7 8] [0 6 9]
[1 2 3 4 5 6 9] [0 7 8]
[1 2 3 4 5 6 8] [0 7 9]
[1 2 3 4 5 6 7] [0 8 9]
[0 4 5 6 7 8 9] [1 2 3]
[0 3 5 6 7 8 9] [1 2 4]
[0 3 4 6 7 8 9] [1 2 5]
[0 3 4 5 7 8 9] [1 2 6]
[0 3 4 5 6 8 9] [1 2 7]
[0 3 4 5 6 7 9] 