# Leave One Out

     Take One Element For Testing and Other For Training

In [3]:
# import liberary

import numpy as np
from sklearn.model_selection import LeaveOneOut

#Data

X = np.array([1, 2, 3, 4])

y = np.array([5,6,7,8])

# Create Object from Class

L_O_O = LeaveOneOut()

splitation = L_O_O.get_n_splits(X)

# get X_tarin , X_text , y_train , y_test 

for train_index , test_index in L_O_O.split(X) :
    X_Train , X_Test = X[train_index] , X[test_index]
    y_Train , y_Test = y[train_index] , y[test_index]
    
    print(f"The X_data ::\n\n{X}\n===\nThe y_data ::\n\n{y}\n===\nThe X_Train ::\n\n{X_Train}\n===\n\
The X_test :: \n\n{X_Test}\nThe Y_Train :: \n\n {y_Train}\nThe y_Test :: \n\n{y_Test}\n===\n\
The X_shap :: {X.shape}\n==\nThe y_shape :: {y.shape}\n==\nThe X_Train_shape :: {X_Train.shape}\n==\n\
The X_Test_shape :: {X_Test.shape}\n===\nThe y_Train_shape:: {y_Train.shape}\n==\nThe y_Test_Shape :: \
{y_Test.shape}\n===\nThe Train_Index :: {train_index}\n===\nThe Test_Index :: {test_index}\n\n*********\n")
    

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[2 3 4]
===
The X_test :: 

[1]
The Y_Train :: 

 [6 7 8]
The y_Test :: 

[5]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (3,)
==
The X_Test_shape :: (1,)
===
The y_Train_shape:: (3,)
==
The y_Test_Shape :: (1,)
===
The Train_Index :: [1 2 3]
===
The Test_Index :: [0]

*********

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[1 3 4]
===
The X_test :: 

[2]
The Y_Train :: 

 [5 7 8]
The y_Test :: 

[6]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (3,)
==
The X_Test_shape :: (1,)
===
The y_Train_shape:: (3,)
==
The y_Test_Shape :: (1,)
===
The Train_Index :: [0 2 3]
===
The Test_Index :: [1]

*********

The X_data ::

[1 2 3 4]
===
The y_data ::

[5 6 7 8]
===
The X_Train ::

[1 2 4]
===
The X_test :: 

[3]
The Y_Train :: 

 [5 6 8]
The y_Test :: 

[7]
===
The X_shap :: (4,)
==
The y_shape :: (4,)
==
The X_Train_shape :: (3,)
==
The X_Te

In [1]:
import numpy as np
from sklearn.model_selection import LeaveOneOut
X = np.array([1, 2, 3, 4])
y = np.array([5,6,7,8])
loo = LeaveOneOut()
loo.get_n_splits(X)
print(loo)
LeaveOneOut()
for train_index, test_index in loo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


LeaveOneOut()
TRAIN: [1 2 3] TEST: [0]
X_train 
 [2 3 4]
X_test 
 [1]
y_train 
 [6 7 8]
y_test 
 [5]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [1 3 4]
X_test 
 [2]
y_train 
 [5 7 8]
y_test 
 [6]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [1 2 4]
X_test 
 [3]
y_train 
 [5 6 8]
y_test 
 [7]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [1 2 3]
X_test 
 [4]
y_train 
 [5 6 7]
y_test 
 [8]
*********************


In [4]:
from sklearn.model_selection import LeaveOneOut
X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))
 

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]
