# Repeated Stratified KFold

     Apply Repeated on tratified KFold

In [3]:
# import liberary

import numpy as np
from sklearn.model_selection import RepeatedStratifiedKFold

#Data

X = np.array([[1, 2],
              [3, 4],
              [5, 6], 
              [7, 8]])

y = np.array([0,0,1,1])

# Create Object from Class

R_S_K_F = RepeatedStratifiedKFold( n_splits = 2 , n_repeats = 2 , random_state = 36851234)

splitation = R_S_K_F.get_n_splits(X , y)

# get X_tarin , X_text , y_train , y_test Based on repeated stratified KFold

for train_index , test_index in R_S_K_F.split(X , y) :
    X_Train , X_Test = X[train_index] , X[test_index]
    y_Train , y_Test = y[train_index] , y[test_index]
    
    print(f"The X_data ::\n\n{X}\n===\nThe y_data ::\n\n{y}\n===\nThe X_Train ::\n\n{X_Train}\n===\n\
The X_test :: \n\n{X_Test}\nThe Y_Train :: \n\n {y_Train}\nThe y_Test :: \n\n{y_Test}\n===\n\
The X_shap :: {X.shape}\n==\nThe y_shape :: {y.shape}\n==\nThe X_Train_shape :: {X_Train.shape}\n==\n\
The X_Test_shape :: {X_Test.shape}\n===\nThe y_Train_shape:: {y_Train.shape}\n==\nThe y_Test_Shape :: \
{y_Test.shape}\n===\nThe Train_Index :: {train_index}\n===\nThe Test_Index :: {test_index}\n\n*********\n")
    

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[0 0 1 1]
===
The X_Train ::

[[3 4]
 [5 6]]
===
The X_test :: 

[[1 2]
 [7 8]]
The Y_Train :: 

 [0 1]
The y_Test :: 

[0 1]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [1 2]
===
The Test_Index :: [0 3]

*********

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[0 0 1 1]
===
The X_Train ::

[[1 2]
 [7 8]]
===
The X_test :: 

[[3 4]
 [5 6]]
The Y_Train :: 

 [0 1]
The y_Test :: 

[0 1]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [0 3]
===
The Test_Index :: [1 2]

*********

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[0 0 1 1]
===
The X_Train ::

[[3 4]
 [7 8]]
===
The X_test :: 

[[1 2]
 [5 6]]
The Y_Tra

In [2]:
import numpy as np
from sklearn.model_selection import RepeatedStratifiedKFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0,0,1,1])
rskf = RepeatedStratifiedKFold(n_splits=2, n_repeats=2,random_state=36851234)
for train_index, test_index in rskf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TRAIN: [1 2] TEST: [0 3]
X_train 
 [[3 4]
 [5 6]]
X_test 
 [[1 2]
 [7 8]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 3] TEST: [1 2]
X_train 
 [[1 2]
 [7 8]]
X_test 
 [[3 4]
 [5 6]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [1 3] TEST: [0 2]
X_train 
 [[3 4]
 [7 8]]
X_test 
 [[1 2]
 [5 6]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 2] TEST: [1 3]
X_train 
 [[1 2]
 [5 6]]
X_test 
 [[3 4]
 [7 8]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
