# Repeated KFold

In [ ]:
#Import Libraries
from sklearn.model_selection import RepeatedKFold
#----------------------------------------------------

#KFold Splitting data

Rkf = RepeatedKFold(n_splits = n, random_state = n , n_repeats = n )

#KFold Data
for train_index, test_index in Rkf.split(X):
    print('Train Data is : \n', train_index)
    print('Test Data is  : \n', test_index)
    print('-------------------------------')
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train Shape is  ' , X_train.shape)
    print('X_test Shape is  ' , X_test.shape)
    print('y_train Shape is  ' ,y_train.shape)
    print('y_test Shape is  ' , y_test.shape)
    print('========================================')

In [2]:
import numpy as np
from sklearn.model_selection import RepeatedKFold

X = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

y = np.array([11, 22, 33, 44])


R_K_F = RepeatedKFold( n_splits= 2 , random_state =40 , n_repeats = 4 )

for train_index , test_index in R_K_F.split(X) :
    X_Train , X_Test = X[train_index] , X[test_index]
    y_Train , y_Test = y[train_index] , y[test_index]
    

    print(f"The X_data ::\n\n{X}\n===\nThe y_data ::\n\n{y}\n===\nThe X_Train ::\n\n{X_Train}\n===\n\
The X_test :: \n\n{X_Test}\nThe Y_Train :: \n\n {y_Train}\nThe y_Test :: \n\n{y_Test}\n===\n\
The X_shap :: {X.shape}\n==\nThe y_shape :: {y.shape}\n==\nThe X_Train_shape :: {X_Train.shape}\n==\n\
The X_Test_shape :: {X_Test.shape}\n===\nThe y_Train_shape:: {y_Train.shape}\n==\nThe y_Test_Shape :: \
{y_Test.shape}\n===\nThe Train_Index :: {train_index}\n===\nThe Test_Index :: {test_index}\n\n**********\n")
    

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[11 22 33 44]
===
The X_Train ::

[[3 4]
 [5 6]]
===
The X_test :: 

[[1 2]
 [7 8]]
The Y_Train :: 

 [22 33]
The y_Test :: 

[11 44]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [1 2]
===
The Test_Index :: [0 3]

**********

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[11 22 33 44]
===
The X_Train ::

[[1 2]
 [7 8]]
===
The X_test :: 

[[3 4]
 [5 6]]
The Y_Train :: 

 [11 44]
The y_Test :: 

[22 33]
===
The X_shap :: (4, 2)
==
The y_shape :: (4,)
==
The X_Train_shape :: (2, 2)
==
The X_Test_shape :: (2, 2)
===
The y_Train_shape:: (2,)
==
The y_Test_Shape :: (2,)
===
The Train_Index :: [0 3]
===
The Test_Index :: [1 2]

**********

The X_data ::

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
===
The y_data ::

[11 22 33 44]
===
The X_Train ::

[[1 2]
 [5 6]]
===
The X_test :: 

[[

In [5]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])


rkf = RepeatedKFold(n_splits=4, n_repeats=4, random_state=44)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
 [11 22 33]
y_test 
 [44]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
