# Shuffle Split

    Split data with random method Based on precentage we givein to it

In [1]:
import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])
y = np.array([1, 2, 1, 2, 1, 2])
rs = ShuffleSplit(n_splits=5, test_size=.1, random_state=0)
rs.get_n_splits(X)

print(rs)

for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

ShuffleSplit(n_splits=5, random_state=0, test_size=0.1, train_size=None)
TRAIN: [2 1 3 0 4] TEST: [5]
TRAIN: [3 4 0 2 5] TEST: [1]
TRAIN: [5 1 2 4 0] TEST: [3]
TRAIN: [2 3 4 1 0] TEST: [5]
TRAIN: [4 3 5 1 0] TEST: [2]


In [2]:
import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])
y = np.array([1, 2, 1, 2, 1, 2])
rs = ShuffleSplit(n_splits=5, train_size=0.5, test_size=.25,random_state=0)
rs.get_n_splits(X)

print(rs)

rs = ShuffleSplit(n_splits=5, train_size=0.5, test_size=.25,random_state=0)
for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)


ShuffleSplit(n_splits=5, random_state=0, test_size=0.25, train_size=0.5)
TRAIN: [1 3 0] TEST: [5 2]
TRAIN: [4 0 2] TEST: [1 3]
TRAIN: [1 2 4] TEST: [3 5]
TRAIN: [3 4 1] TEST: [5 2]
TRAIN: [3 5 1] TEST: [2 4]


In [3]:
import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.arange(10)

n=0.1
#n=0.3
#n=0.5
#n=0.7
#n=0.9

ss = ShuffleSplit(n_splits=5, test_size=n,random_state=0)
for train_index, test_index in ss.split(X):
    print("%s %s" % (train_index, test_index))


[8 4 9 1 6 7 3 0 5] [2]
[5 1 2 9 8 0 6 7 4] [3]
[3 8 4 5 1 0 6 9 7] [2]
[1 9 2 7 5 8 0 3 4] [6]
[2 7 4 1 0 6 8 9 3] [5]
