# Train_Test_Split

In [ ]:
#Import Libraries
from sklearn.model_selection import train_test_split
#----------------------------------------------------

#Splitting data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44, shuffle =True)

#Splitted Data
print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(10) .reshape(5,2)

y = list(range(5))

X_train , X_test , y_train , y_test = train_test_split( X , y , test_size = 0.33 , random_state = 42  )


print(f"The X_Train ::\n\n{X_train}\n===\nThe X_Test ::\n\n{X_test}\n===\nThe y_Train ::\n\n{y_train}\
\n===\nThe Y_Test ::\n\n{y_test}\n===\n X_data ::\n\n{X}\nThe y_data ::\n\n{y}")

The X_Train ::

[[4 5]
 [0 1]
 [6 7]]
===
The X_Test ::

[[2 3]
 [8 9]]
===
The y_Train ::

[2, 0, 3]
===
The Y_Test ::

[1, 4]
===
 X_data ::

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
The y_data ::

[0, 1, 2, 3, 4]


In [4]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(10) .reshape(5,2)

y = list(range(5))

X_train , X_test , y_train , y_test = train_test_split( X , y , test_size = 0.33 , random_state = 42 ,shuffle =True  )


print(f"The X_Train ::\n\n{X_train}\n===\nThe X_Test ::\n\n{X_test}\n===\nThe y_Train ::\n\n{y_train}\
\n===\nThe Y_Test ::\n\n{y_test}\n===\n X_data ::\n\n{X}\nThe y_data ::\n\n{y}")

The X_Train ::

[[4 5]
 [0 1]
 [6 7]]
===
The X_Test ::

[[2 3]
 [8 9]]
===
The y_Train ::

[2, 0, 3]
===
The Y_Test ::

[1, 4]
===
 X_data ::

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
The y_data ::

[0, 1, 2, 3, 4]
