# Array CreaTion 1

In [8]:
# Its array cosist of 2 >>>>>rows  and 1 >> colums

import numpy as np
A1 = np.array([2,6])
print(A1)
print(A1.shape)
print("=================")

# Its arry consist 1 >> row and 2 >> olumns

A2 = np.array([[2,6]])
print(A2)
print(A2.shape)
print("=================")

 # Its array consist of 3 >>rows ana 3 >>columns 

A3 = np.array([[2,6],[1,3],[4,8]])
print(A3)
print(A3.shape)
print("========================")




# Its array consist of 5 >> rows and 1 >> columns

A4 = np.array([2,4,3,5,8])
print(A4)
print(A4.shape)


# Its array consist of 1 >> rows and 5 >> columns


A4 = np.array([[2,4,3,5,8]])
print(A4)
print(A4.shape)


[2 6]
(2,)
[[2 6]]
(1, 2)
[[2 6]
 [1 3]
 [4 8]]
(3, 2)
[2 4 3 5 8]
(5,)
[[2 4 3 5 8]]
(1, 5)


# Array CreaTion 2


In [13]:
# create Array by Ay number and  size

#

A = np.zeros(3)
print(A)
print(A.shape)
print("=================")

B = np.zeros((3,3))
print(B)
print("===================")

C = np.ones(5)
print(C)
print(C.shape)
print("===================")

D = np.ones((4,4))
print(D)
print(D.shape)
print("====================")

E = np.ones((3,3),dtype="complex")
print(E)
print("=======================")

F = np.zeros((3,3),dtype="complex")
print(F)
print("===================")

# create arry consist any number by any shape

A1 = np.full((3,3) ,5)

print("A1" ,A1)
print("=================")

# To create Array by range 
# range take int only  But arange Take int or float

A2 = np.arange(10)
A3 = np.arange(1,10,2)

print("A2" ,A2)
print(A2.shape)

print("=================")

print("A3",A3)
print(A3.shape)

print("=================")

# To Create Array by random numbers 

A4 = np.random.random((2,2) )

print("A4",A4)
print("=================")






# To create Array by random int Numbers

A5 = np.random.randint(1,10,(3,3))
A6 = np.random.randint(0,10,(2,2))

print("A5", A5)
print("=================")
print("A6",A6)
print("=================")

# To Create Array using Linespace
A7 = np.linspace(1,10,20)
print("A7",A7)


[0. 0. 0.]
(3,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
(5,)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
A1 [[5 5 5]
 [5 5 5]
 [5 5 5]]
A2 [0 1 2 3 4 5 6 7 8 9]
(10,)
A3 [1 3 5 7 9]
(5,)
A4 [[0.96181644 0.34194262]
 [0.34933985 0.18018094]]
A5 [[5 3 2]
 [3 4 1]
 [1 4 9]]
A6 [[5 1]
 [9 2]]
A7 [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


# Array Creation

In [2]:
import numpy as np
A = np.zeros(5)    #Float
A1=np.zeros((3,3),dtype="int64")  # Int
A2=np.ones((3,3),dtype="complex")  # Complex
A3=np.full((5,5),4)

print(A)
print("=================")

print(A1)
print("=================")

print(A2)
print("=====================")
print(A3)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
