# Array Resheping

In [7]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8])   # one_dimentional Array

print("A" , A)
print(A.shape)
print(A.dtype)
print("=================")

# To covert Array into Two_dimentional

A1 = A.reshape((2,4))
print("A1" , A1)
print(A1.shape)
print(A1.dtype)

print("=================")
A2 = A.reshape((4,2))
print("A2" , A2)
print(A2.shape)
print(A2.dtype)
print("=================")

# To covert Array into 3_dimentional
A3 = A.reshape((2,2,2))
print("A3" , A3)
print(A3.shape)
print(A3.dtype)





A [1 2 3 4 5 6 7 8]
(8,)
int32
A1 [[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int32
A2 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
int32
A3 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
int32


# order Array >>>>  ("F")  ,, ("C") 

In [3]:
import numpy as np
Arr = np.array([[1,2,3,4,5,6,7,8]])
print("Arr" , Arr)
print(Arr.shape)
print("=================")

# Convert Array into 2_dimentional

Arr1 = Arr.reshape( (2,4) , order = "F")
print("Arr1",Arr1)
print("===========================")

Arr2 = Arr.reshape((4,2) , order = "F")
print( "Arr2",Arr2)
print("===========================")

Arr3 = Arr.reshape((2,4), order = "C")
print("Arr3" , Arr3)
print("===========================")

Arr4 = Arr.reshape((4,2), order = "C")
print("Arr3",Arr4)

Arr [[1 2 3 4 5 6 7 8]]
(1, 8)
Arr1 [[1 3 5 7]
 [2 4 6 8]]
Arr2 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Arr3 [[1 2 3 4]
 [5 6 7 8]]
Arr3 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Array Flatten 

In [6]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]]) # 2_dimentional
print("a",a)
print("===========================")

# convert Array into 1_dimentional

a1 = a.flatten()
print("a1",a1)
print(a1.shape)
print("===========================")

a2 = a.reshape((8,))

print("a2",a2)
print(a1.shape)




a [[1 2 3 4]
 [5 6 7 8]]
a1 [1 2 3 4 5 6 7 8]
(8,)
a2 [1 2 3 4 5 6 7 8]
(8,)
