# Array Indexing

In [8]:
import numpy as np

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print("A" , A)
print("===========================")
print(A.reshape((12,)))
print("===========================")
print(A.flatten())
print("===========================")

print(A[2,3])
print("===========================")
print(A[0,2])
print("===========================")
print(A[2][2])
print("===========================")
print(A[1][3])

A [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
3
11
8


# Integer rray Indexing

In [2]:
import numpy as np
a = np.array([[5,2,3],
              [-2,4,2],
              [2,-3,1]])



print(a)
print("==========================")
print(a[[0,1,2],[0,1,2]])
print("==========================")
print(a[[0,2,1],[2,1,0]])

[[ 5  2  3]
 [-2  4  2]
 [ 2 -3  1]]
[5 4 1]
[ 3 -3 -2]


In [3]:
import numpy as np
A= np.arange(70)
print(A)
print("=================")
C=A.reshape(2,5,7)
print(C)
print("=================")
print(C[1])
print("=================")
print(C[0])
print("=================")
C[1,2,3] = 1111
print(C[1])
print("=================")



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]]

 [[35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]]]
[[35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[  35   36   37   38   39   40   41]
 [  42   43   44   45   46   47   48]
 [  49   50   51 1111   53   54   55]
 [  56   57   58   59   60   61   62]
 [  63   64   65   66   67   68   69]]


# Boolean Array Indexing

In [10]:
import numpy as np
a = np.array([[5,2,3],
              [-2,4,2],
              [2,-3,1]])

print(a>0)    # To Get Ture or False
print("==========================")

print(a<0)    # To Get Ture or False
print("==========================")

print(a[a>0])   # To get Numbers in array > 0
print("==========================")

print(a[a<0])   # To get Numbers in array < 0 

[[ True  True  True]
 [False  True  True]
 [ True False  True]]
[[False False False]
 [ True False False]
 [False  True False]]
[5 2 3 4 2 2 1]
[-2 -3]


In [7]:
import numpy as np
A=np.arange(10)
print(A)
print("=================")
B= 0==(A%2)
print(B)
print("=================")
print(A[B])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


# Array Slicing

In [7]:
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print(A[ : , :2])
print("==========================")
print(A[ 1 : , 1 : ])
print("==========================")
print(A[ 1 : 2 , 2 : 3 ])
print("==========================")
print(A[1,2])


[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 6  7  8]
 [10 11 12]]
[[7]]
7
