# Linear algebra 

In [1]:
# X + 2*Y = 8
# 3*X + 4*Y = 18

# Solving linear algebra equation

import numpy as np
A = np.array([[1,2] , [3,4]])   # cofficientMatrix
B = np.array([8,18])   # Constants Matrix

print(np.linalg.solve(A,B))



[2. 3.]


In [4]:
import numpy as np

A = np.array([[6,1,1],
              [4,-2,5],
              [2,8,7]])


print(A)
print("========================")

# Ranke of matrix 

print(np.linalg.matrix_rank(A))
print("========================")

# Determinant of matrix
print(np.linalg.det(A))
print("========================")

# inverse of matrix
print(np.linalg.inv(A))
print("========================")


# Exponeniation of matrix
print(np.linalg.matrix_power(A,3))
print("========================")

# To trace matrix

print(np.trace(A))


[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
3
-306.0
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[336 162 228]
 [406 162 469]
 [698 702 905]]
11


In [9]:
import numpy as np
A_M = np.matrix([[ 3 , 1 , 4 ],[ 1 , 5 , 9 ],[ 2 , 6 , 5 ]])
print(A_M)
print("===========================")
print(A_M.T)
print("===========================")
print(A_M.I)
print("===========================")
print(A_M.H)
print("===========================")
print( A_M * A_M.T)
print("===========================")
print( A_M * A_M.I)
print("===========================")
print( A_M * A_M.H)

print("===========================")
print("===========================")
print("===========================")
A_M_R = np.matrix([[11,22,33],
                   [33,22,11],
                   [22,33,22]])
print(A_M_R)
print("===========================")
A_M_Inv = A_M.I
N_M = A_M_R * A_M_Inv
print(N_M)

print("===========================")
print("===========================")
print(N_M[0])
print("===========================")
print(N_M[1])
print("===========================")
print(N_M[2])
print("===========================")
print("===========================")
print( A_M * N_M - A_M.I)
print("===========================")
print("===========================")
print(N_M * A_M + A_M.H)



[[3 1 4]
 [1 5 9]
 [2 6 5]]
[[3 1 2]
 [1 5 6]
 [4 9 5]]
[[ 0.32222222 -0.21111111  0.12222222]
 [-0.14444444 -0.07777778  0.25555556]
 [ 0.04444444  0.17777778 -0.15555556]]
[[3 1 2]
 [1 5 6]
 [4 9 5]]
[[ 26  44  32]
 [ 44 107  77]
 [ 32  77  65]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.38777878e-16]
 [ 5.55111512e-17 -1.38777878e-16  1.00000000e+00]]
[[ 26  44  32]
 [ 44 107  77]
 [ 32  77  65]]
[[11 22 33]
 [33 22 11]
 [22 33 22]]
[[ 1.83333333  1.83333333  1.83333333]
 [ 7.94444444 -6.72222222  7.94444444]
 [ 3.3        -3.3         7.7       ]]
[[1.83333333 1.83333333 1.83333333]]
[[ 7.94444444 -6.72222222  7.94444444]]
[[ 3.3 -3.3  7.7]]
[[ 26.32222222 -14.21111111  44.12222222]
 [ 71.4        -61.4        110.6       ]
 [ 67.78888889 -53.34444444  89.98888889]]
[[14. 23. 35.]
 [34. 27. 17.]
 [26. 42. 27.]]


# indentity Matrix Arr


In [4]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Solve Func

In [13]:
from numpy.linalg import solve
print(solve( A_M , A_M_R))
print("===========================")
print("===========================")
print(solve( A_M , A_M_Inv))
print("===========================")
print("===========================")
print(solve( A_M_R , A_M_Inv))


[[-7.33333333e-01  6.47777778e+00  1.10000000e+01]
 [ 1.46666667e+00  3.54444444e+00  2.64603154e-16]
 [ 2.93333333e+00 -2.44444444e-01 -8.14163551e-17]]
[[ 0.13975309 -0.02987654 -0.03358025]
 [-0.02395062  0.08197531 -0.07728395]
 [-0.0182716  -0.0508642   0.07506173]]
[[-0.00656566 -0.01489899  0.0229798 ]
 [-0.0040404   0.02929293 -0.03131313]
 [ 0.01464646 -0.0209596   0.01691919]]


# Eig Func

In [15]:
from numpy.linalg import eig
print(eig(A_M))
print("===========================")
print("===========================")
print("===========================")

print(eig(A_M_Inv))
print("===========================")
print("===========================")
print("===========================")

print(eig(A_M_R))
print("===========================")
print("===========================")
print("===========================")

print(eig(N_M))

(array([13.08576474,  2.58000566, -2.66577041]), matrix([[-0.31542644, -0.95117074, -0.32372474],
        [-0.72306109,  0.30781323, -0.70222933],
        [-0.61456393,  0.02291827,  0.63409484]]))
(array([-0.37512608,  0.38759605,  0.07641892]), matrix([[ 0.32372474,  0.95117074,  0.31542644],
        [ 0.70222933, -0.30781323,  0.72306109],
        [-0.63409484, -0.02291827,  0.61456393]]))
(array([69.41243152 +0.j        , -7.20621576+10.07334952j,
       -7.20621576-10.07334952j]), matrix([[ 0.55918937+0.j        ,  0.51046942-0.31693554j,
          0.51046942+0.31693554j],
        [ 0.53595231+0.j        , -0.67717579+0.j        ,
         -0.67717579-0.j        ],
        [ 0.63250484+0.j        ,  0.26656828+0.33067678j,
          0.26656828-0.33067678j]]))
(array([-6.60956927,  2.63975289,  6.7809275 ]), matrix([[ 0.26046574, -0.82040031,  0.46412262],
        [-0.92590673, -0.54225549,  0.63586563],
        [-0.27359518,  0.18138994,  0.61665639]]))


In [1]:
import numpy as np
F_M = np.array([[ 3 , 1 , 4 ] , [ 1 , 5 , 9 ] , [ 2 , 6 , 5 ]])
print(F_M)

[[3 1 4]
 [1 5 9]
 [2 6 5]]
