# Saving Array

In [4]:
import numpy as np

A= np.array([[1,2,3],
             [4,5,6]])

B = np.array([[4,5,6],
              [3,2,1]]) 

print(A)
print("========================")
print(B)
print("========================")

# Saving Single Array

print(np.save("A.npy",A))
print("========================")
print(np.save("B.npy",B))


print("========================")
print("========================")

# Saving multi Arrays

print(np.savez("AB.npz", X=A , Y=B))


[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [3 2 1]]
None
None
None


# Loading Array

In [11]:
import numpy as np

A= np.array([[1,2,3],
             [4,5,6]])

B = np.array([[4,5,6],
              [3,2,1]]) 

print(A)
print("========================")
print(B)
print("========================")

# Loading Single Array

print(np.load("A.npy"))
print("========================")

print(np.load("B.npy"))
print("========================")
print("========================")

# Loading muti Arrays
Arr = np.load("AB.npz")
print(Arr)

print("========================")
print("========================")

print(Arr["X"])
print("========================")
print(Arr["Y"])



[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [3 2 1]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [3 2 1]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [3 2 1]]
