In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
B = np.arange(20).reshape(4,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

To get Max and Min values of Arrays

In [5]:
np.max(A)

11

In [6]:
np.max(B)

19

In [7]:
np.min(A)

0

In [8]:
np.min(B)

0

axis = 0 refer to deal with Rows horizontal   The  result list include values to count of columns

In [24]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
np.max(A , axis = 0)

array([ 8,  9, 10, 11])

In [27]:
np.max(B , axis = 0)

array([15, 16, 17, 18, 19])

In [28]:
np.min(A , axis = 0)

array([0, 1, 2, 3])

In [29]:
np.min(B , axis = 0)

array([0, 1, 2, 3, 4])

axis = 1 refer to deal with Columns Vertical  The  result list include values to count of Rows

In [30]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
np.max(A, axis = 1)

array([ 3,  7, 11])

In [33]:
np.max(B , axis = 1)

array([ 4,  9, 14, 19])

In [34]:
np.min(A , axis = 1)

array([0, 4, 8])

In [35]:
np.min(B, axis = 1)

array([ 0,  5, 10, 15])

v_Stack() and h_Stack()

In [43]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
C = np.array([[15, 16, 17, 18] , [10, 11, 12, 13] , [ 5,  6,  7,  8]])
C

array([[15, 16, 17, 18],
       [10, 11, 12, 13],
       [ 5,  6,  7,  8]])

In [52]:
np.hstack([A , C] )  # addition on rows

array([[ 0,  1,  2,  3, 15, 16, 17, 18],
       [ 4,  5,  6,  7, 10, 11, 12, 13],
       [ 8,  9, 10, 11,  5,  6,  7,  8]])

In [54]:
V = np.vstack([A , C]) # adition on colums
V

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [10, 11, 12, 13],
       [ 5,  6,  7,  8]])

V_Split and h_split

In [60]:
np.hsplit(V , 2) # as Rows

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [15, 16],
        [10, 11],
        [ 5,  6]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [17, 18],
        [12, 13],
        [ 7,  8]])]

In [61]:
np.vsplit(V , 2) # as Colums

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[15, 16, 17, 18],
        [10, 11, 12, 13],
        [ 5,  6,  7,  8]])]