# SVR_Classifier_Model 

In [45]:
# import Liberaries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error , mean_squared_error , median_absolute_error

In [25]:
# loading dataset
path = "G:\\Data Field\\D..S..Course\\data.sc.Asem\\Data\\Data\\2.4 SVR\\Earthquakes.csv"
data = pd.read_csv(path)
# present dataset
data

latitude  longitude   depth  mag  gap   dmin   rms  horizontalError  \
0       5.1033   125.3179   44.32  4.3  131  1.970  0.70              5.0   
1      -8.8535   117.1527  116.88  4.9   59  2.991  1.06              6.5   
2       4.7512    96.2239   10.00  5.3  148  0.862  1.29              6.6   
3     -10.1202   118.7274   10.00  4.5   86  3.764  0.95              7.6   
4       1.4361   127.0142  120.78  4.5  105  0.748  0.76              8.0   
...        ...        ...     ...  ...  ...    ...   ...              ...   
1364    2.2514   126.9574   47.42  4.3  113  1.525  0.68              9.9   
1365  -11.1391   116.2387   32.76  4.3  121  3.355  1.25              7.7   
1366   -2.8106   102.2034  164.67  4.3  102  1.713  0.64              5.8   
1367   -8.4613   121.6951  181.63  4.5   76  0.563  1.25              8.0   
1368   -8.1306   119.6653  168.28  5.1   50  2.594  1.19              7.1   

      depthError  magError  meter  
0            9.3     0.126   18.0  
1            7.3     0.091   38.0  
2            1.8     0.073   18.0  
3            1.9     0.084   42.0  
4            6.6     0.089   37.0  
...          ...       ...    ...  
1364         7.9     0.107   25.0  
1365         6.1     0.154   12.0  
1366         7.7     0.101   28.0  
1367         5.9     0.131   17.0  
1368         4.4     0.060   88.0  

[1369 rows x 11 columns]

In [26]:
# imputing missing data

Imp_missing_data = SimpleImputer(missing_values=np.nan , strategy="mean")

data = Imp_missing_data.fit_transform(data)

data




array([[ 5.103300e+00,  1.253179e+02,  4.432000e+01, ...,  9.300000e+00,
         1.260000e-01,  1.800000e+01],
       [-8.853500e+00,  1.171527e+02,  1.168800e+02, ...,  7.300000e+00,
         9.100000e-02,  3.800000e+01],
       [ 4.751200e+00,  9.622390e+01,  1.000000e+01, ...,  1.800000e+00,
         7.300000e-02,  1.800000e+01],
       ...,
       [-2.810600e+00,  1.022034e+02,  1.646700e+02, ...,  7.700000e+00,
         1.010000e-01,  2.800000e+01],
       [-8.461300e+00,  1.216951e+02,  1.816300e+02, ...,  5.900000e+00,
         1.310000e-01,  1.700000e+01],
       [-8.130600e+00,  1.196653e+02,  1.682800e+02, ...,  4.400000e+00,
         6.000000e-02,  8.800000e+01]])

In [28]:
# Rescalling data using Standarzation model

Rescalling_data = StandardScaler()

data = Rescalling_data.fit_transform(data)
data

array([[ 1.11009733,  0.6094858 , -0.44639344, ...,  0.68491471,
         0.09052609, -0.42683887],
       [-1.38056298, -0.20501984,  0.1144867 , ...,  0.16241702,
        -0.60576134,  0.23053864],
       [ 1.04726334, -2.29273669, -0.71168294, ..., -1.27445165,
        -0.96385201, -0.42683887],
       ...,
       [-0.30217745, -1.69626184,  0.4838977 , ...,  0.26691656,
        -0.40682207, -0.09815011],
       [-1.31057294,  0.24809955,  0.61499647, ..., -0.20333137,
         0.18999572, -0.45970774],
       [-1.25155788,  0.0456203 ,  0.51180257, ..., -0.59520464,
        -1.22247306,  1.8739824 ]])

* Spliting data into Input ,, outPut data

In [31]:
X = data[ : , : -1]
y = data[ : , -1]

In [34]:
print(f"X_data ::\n{X[:10]}\n======\nThe Y_data ::: \n {y[:10]}\n=====\n\
The X_data_shap :: {X.shape}\n=====\nThe y_data_shap :: {y.shape}")

X_data ::
[[ 1.11009733  0.6094858  -0.44639344 -0.52054698  0.67079943 -0.15615985
  -0.58750616 -1.23101894  0.68491471  0.09052609]
 [-1.38056298 -0.20501984  0.1144867   1.07073434 -0.93759188  0.29056192
   0.79695658 -0.65892819  0.16241702 -0.60576134]
 [ 1.04726334 -2.29273669 -0.71168294  2.13158856  1.0505585  -0.64094705
   1.68147444 -0.62078881 -1.27445165 -0.96385201]
 [-1.60661188 -0.04793832 -0.71168294  0.00988013 -0.33444514  0.62877537
   0.3739263  -0.23939498 -1.24832677 -0.74501882]
 [ 0.45566727  0.77869732  0.14463324  0.00988013  0.08999146 -0.69082588
  -0.35676237 -0.08683744 -0.02045718 -0.64554919]
 [ 0.30749611  0.7053188  -0.47576698 -0.25533343  0.26870161 -0.53681406
  -1.85659701  0.06572009  0.13629213  0.5480864 ]
 [-1.42840675  0.32581735  0.31090297  1.86637501 -1.04928572 -0.783583
   0.3739263  -1.8031097  -0.12495672 -1.00363987]
 [-0.03959881 -1.94714139 -0.43541701  0.54030723  1.89943169 -0.08396682
  -1.01053645  0.29455639  0.37141609 -0.66

* Spliting data into Training and testing data

In [37]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size = 0.33 , random_state = 44 , shuffle = True)

# present data

print(f"The X_train_data ::\n{X_train[:10]}\n====\nThe X_test_data ::\n {X_test[:10]}\n====\nThe y_train_data :: \
\n{y_train[:10]}\n=====\nThe y_test_data :: \n{y_test[:10]}\n======\nThe X_tarin_shap :: {X_train.shape}\n=====\n\
The X_test_shap :: {X_test.shape}\n=====\nThe y_train_shap :: {y_train.shape}\n===\nThe y_test_shap ::\
{y_test.shape}")

The X_train_data ::
[[ 1.01758627  0.60126613 -0.51843592 -0.52054698  0.134669    0.07223267
   1.14307227 -0.04869806 -1.22220188 -0.04873139]
 [ 0.80147731  0.74322505 -0.32147857 -0.52054698  1.56435017  0.15405145
   0.64312739  1.20990159  0.26691656  1.10511634]
 [-1.53108974 -0.72006607 -0.51843592 -0.52054698  1.58668894 -0.01614911
  -0.31830508  0.21827763 -1.22220188  1.32394954]
 [ 0.73475299  0.66970687 -0.71168294  0.00988013 -0.49081652  0.13786271
   0.2970117   0.10385948 -1.24832677  0.13031394]
 [ 0.2294756  -2.0669451  -0.39955036 -0.78576054  1.00588096 -0.38367731
   0.41238359 -0.04869806  0.65878983  0.38893499]
 [-1.23381946 -0.55283964  0.36593972 -1.31618765 -0.15573499 -0.7341417
   1.41227335 -0.20125559  0.21466679 -0.04873139]
 [ 0.9855893  -2.25976823 -0.51766294  0.00988013 -0.82589804 -0.62169558
  -0.08756129 -0.46823128  0.42366586 -0.38692815]
 [-1.54386712 -0.74901448 -0.71168294 -0.78576054  1.02821973 -0.0642778
   1.10461497  0.37083516 -1.2222

* define SVR_Model To classifier data

In [48]:
SVR_Model = SVR(C =20 , kernel = "linear" , epsilon = 0.01)

SVR_Model.fit(X_train , y_train)

Model_Coef = SVR_Model.coef_
Model_intercept = SVR_Model.intercept_
Model_training_Score = SVR_Model.score(X_train , y_train)
Model_Testing_Score = SVR_Model.score(X_test , y_test)
y_pred = SVR_Model.predict(X_test)
MAE = mean_absolute_error(y_test , y_pred , multioutput="uniform_average")
MSE = mean_squared_error(y_test , y_pred , multioutput="uniform_average")
Mid_A_E = median_absolute_error(y_test , y_pred )


In [49]:
print(f"The Model_Coef :: \n{Model_Coef}\n====\nThe Model_intercept :: {Model_intercept}\n=======\n\
The Model_training_Score :: {Model_training_Score}\n=====\n The Model_Testing_Score :: \
{Model_Testing_Score}\n========\n The y_pred :: \n{y_pred[:5]}\nThe y_real :: \n{y_test[:5]}\n===\n\
The MAE :: {MAE}\n======\nThe MSE :: {MSE}\n=======\nThe mid_A_E :: {Mid_A_E}")

The Model_Coef :: 
[[ 0.00511112 -0.01150141  0.0239237   0.14912502 -0.01580753  0.01255019
  -0.01337433 -0.01287564 -0.0033069  -0.45530721]]
====
The Model_intercept :: [-0.20821028]
The Model_training_Score :: 0.4131434798725978
=====
 The Model_Testing_Score :: 0.4578977132675841
 The y_pred :: 
[-0.38297879 -0.48743431 -0.77783512 -0.67803766  0.63987466]
The y_real :: 
[-0.49257662 -0.55831437 -0.68978987 -0.65692099  1.77537577]
===
The MAE :: 0.3634588842298545
The MSE :: 0.46405839821382355
The mid_A_E :: 0.1296987698130379


* Changing Hyperprameter of SVR_Model

In [51]:
SVR_Model = SVR(C =20 , kernel = "rbf" , epsilon = 0.01)

SVR_Model.fit(X_train , y_train)

#Model_Coef = SVR_Model.coef_
#Model_intercept = SVR_Model.intercept_
Model_training_Score = SVR_Model.score(X_train , y_train)
Model_Testing_Score = SVR_Model.score(X_test , y_test)
y_pred = SVR_Model.predict(X_test)
MAE = mean_absolute_error(y_test , y_pred , multioutput="uniform_average")
MSE = mean_squared_error(y_test , y_pred , multioutput="uniform_average")
Mid_A_E = median_absolute_error(y_test , y_pred )


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [52]:
print(f"The Model_training_Score :: {Model_training_Score}\n=====\n The Model_Testing_Score :: \
{Model_Testing_Score}\n========\n The y_pred :: \n{y_pred[:5]}\nThe y_real :: \n{y_test[:5]}\n===\n\
The MAE :: {MAE}\n======\nThe MSE :: {MSE}\n=======\nThe mid_A_E :: {Mid_A_E}")

The Model_training_Score :: 0.9637569604443499
=====
 The Model_Testing_Score :: 0.8389422230428307
 The y_pred :: 
[-0.53760144 -0.47285802 -0.69748018 -0.65355527  1.05174414]
The y_real :: 
[-0.49257662 -0.55831437 -0.68978987 -0.65692099  1.77537577]
===
The MAE :: 0.15120334530219787
The MSE :: 0.13787105464012797
The mid_A_E :: 0.05365209147113155
