# SVR_Classifier_Model 

In [9]:
# Import Liberaries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error , mean_squared_error , median_absolute_error ,r2_score

In [5]:
# loading dataset

path = "G:\\Data Field\\D..S..Course\\data.sc.Asem\\Data\Data\\2.4 SVR\\satf.csv"
data = pd.read_csv(path)
data

high_GPA  math_SAT  verb_SAT  comp_GPA  univ_GPA
0        3.45       643       589      3.76      3.52
1        2.78       558       512      2.87      2.91
2        2.52       583       503      2.54      2.40
3        3.67       685       602      3.83      3.47
4        3.24       592       538      3.29      3.47
..        ...       ...       ...       ...       ...
100      3.76       605       590      3.74      3.64
101      3.49       692       683      3.27      3.42
102      3.07       680       692      3.19      3.25
103      2.19       617       503      2.98      2.76
104      3.46       516       528      3.28      3.41

[105 rows x 5 columns]

* Handling missing data values


In [6]:

Handlling_data = SimpleImputer(missing_values=np.nan , strategy="mean")
data = Handlling_data.fit_transform(data)
data

array([[  3.45, 643.  , 589.  ,   3.76,   3.52],
       [  2.78, 558.  , 512.  ,   2.87,   2.91],
       [  2.52, 583.  , 503.  ,   2.54,   2.4 ],
       [  3.67, 685.  , 602.  ,   3.83,   3.47],
       [  3.24, 592.  , 538.  ,   3.29,   3.47],
       [  2.1 , 562.  , 486.  ,   2.64,   2.37],
       [  2.82, 573.  , 548.  ,   2.86,   2.4 ],
       [  2.36, 559.  , 536.  ,   2.03,   2.24],
       [  2.42, 552.  , 583.  ,   2.81,   3.02],
       [  3.51, 617.  , 591.  ,   3.41,   3.32],
       [  3.48, 684.  , 649.  ,   3.61,   3.59],
       [  2.14, 568.  , 592.  ,   2.48,   2.54],
       [  2.59, 604.  , 582.  ,   3.21,   3.19],
       [  3.46, 619.  , 624.  ,   3.52,   3.71],
       [  3.51, 642.  , 619.  ,   3.41,   3.58],
       [  3.68, 683.  , 642.  ,   3.52,   3.4 ],
       [  3.91, 703.  , 684.  ,   3.84,   3.73],
       [  3.72, 712.  , 652.  ,   3.64,   3.49],
       [  2.15, 564.  , 501.  ,   2.14,   2.25],
       [  2.48, 557.  , 549.  ,   2.21,   2.37],
       [  3.09, 591.

* Normalizing data using Standerzation model


In [7]:

Rescalling_data = StandardScaler()
data = Rescalling_data.fit_transform(data)
data

array([[ 0.72669875,  0.37238093, -0.15320031,  1.24749308,  0.77999282],
       [-0.57646865, -1.2162901 , -1.38199444, -0.50926141, -0.59061185],
       [-1.0821754 , -0.74903391, -1.52561973, -1.16064229, -1.73652722],
       [ 1.15460446,  1.15737132,  0.05425844,  1.38566478,  0.66764817],
       [ 0.3182433 , -0.58082169, -0.96707694,  0.3197688 ,  0.66764817],
       [-1.89908631, -1.14152911, -1.79691194, -0.96325415, -1.80393401],
       [-0.49866761, -0.93593639, -0.80749329, -0.52900023, -1.73652722],
       [-1.39337956, -1.19759985, -0.99899367, -2.16732183, -2.09603009],
       [-1.276678  , -1.32843158, -0.2489505 , -0.6276943 , -0.34345363],
       [ 0.84340031, -0.1135655 , -0.12128358,  0.55663457,  0.33061424],
       [ 0.78504953,  1.13868107,  0.80430161,  0.95141086,  0.93727532],
       [-1.82128527, -1.02938763, -0.10532521, -1.27907518, -1.42196222],
       [-0.94602358, -0.35653872, -0.26490886,  0.16185828,  0.03851816],
       [ 0.74614901, -0.07618501,  0.4

* Spliting data into input ,, output data becouse its supervised ML_Algo

In [8]:
X = data[ : , : -1]
y = data[ : , -1]

print(f"The X_data :: \n{X}\n=======\nThe y_data :: \n{y}\n======\nThe X_data_shap :: {X.shape}\n====\n\
The y_data_shap :: {y.shape}")

The X_data :: 
[[ 0.72669875  0.37238093 -0.15320031  1.24749308]
 [-0.57646865 -1.2162901  -1.38199444 -0.50926141]
 [-1.0821754  -0.74903391 -1.52561973 -1.16064229]
 [ 1.15460446  1.15737132  0.05425844  1.38566478]
 [ 0.3182433  -0.58082169 -0.96707694  0.3197688 ]
 [-1.89908631 -1.14152911 -1.79691194 -0.96325415]
 [-0.49866761 -0.93593639 -0.80749329 -0.52900023]
 [-1.39337956 -1.19759985 -0.99899367 -2.16732183]
 [-1.276678   -1.32843158 -0.2489505  -0.6276943 ]
 [ 0.84340031 -0.1135655  -0.12128358  0.55663457]
 [ 0.78504953  1.13868107  0.80430161  0.95141086]
 [-1.82128527 -1.02938763 -0.10532521 -1.27907518]
 [-0.94602358 -0.35653872 -0.26490886  0.16185828]
 [ 0.74614901 -0.07618501  0.40534248  0.77376153]
 [ 0.84340031  0.35369068  0.32555065  0.55663457]
 [ 1.17405472  1.11999082  0.69259306  0.77376153]
 [ 1.6214107   1.49379577  1.3628444   1.40540359]
 [ 1.25185576  1.662008    0.85217671  1.0106273 ]
 [-1.80183501 -1.10414861 -1.55753646 -1.95019487]
 [-1.15997644 -1

* Spliting data into Traning data to fit model and testing data to estimate

In [13]:
X_train , X_test , y_train , y_test = train_test_split( X , y , test_size= 0.33 , random_state = 44 , shuffle = True)

print(f"The X_train :: \n{X_train[:10]}\n========\nThe X_test :: \n{X_test[:10]}\n=======\nThe y_train :: \n{y_train[:10]}\
\n======\nThe y_test :: \n{y_test[:10]}\n======\nThe X_train_shap :: {X_train.shape}\n====\nThe X_test_shap ::\
\n{X_test.shape}\n=====\nThe y_train_shap ::{y_train.shape}\n=====\nthe y_test_shap ::{y_test.shape}")

The X_train :: 
[[ 0.72669875  0.37238093 -0.15320031  1.24749308]
 [ 0.25989252  0.97046885  0.5330094   0.49741813]
 [ 1.44635836  1.77414948  2.12884594  1.28697071]
 [ 0.27934278  1.2695128   1.01176036  0.30002998]
 [-1.72403397 -0.1135655  -1.52561973 -0.29213445]
 [ 1.64086096  1.69938849  1.71392844  1.34618715]
 [ 0.70724849  0.35369068  0.15000863  0.35924642]
 [-1.62678267 -1.02938763 -1.27028588  0.49741813]
 [ 0.25989252 -0.07618501 -0.40853415 -0.56847786]
 [ 0.1237407  -0.30046798  0.40534248  0.30002998]]
The X_test :: 
[[-0.10966242 -1.04807787  0.05425844  0.08290302]
 [-2.03523813 -1.02938763 -1.30220261 -1.8515008 ]
 [-1.91853657 -1.29105109 -1.89266213  1.08958256]
 [-1.39337956 -1.19759985 -0.99899367 -2.16732183]
 [ 0.220992    0.50321266  1.3628444  -0.03552987]
 [-1.15997644 -1.23498035 -0.79153492 -1.81202317]
 [ 0.06538992  1.15737132  1.52242805  0.30002998]
 [ 0.94065161  1.75545924  0.80430161  0.71454509]
 [-1.72403397 -1.14152911 -1.46178627 -2.02915013]

* Appling  SVR_Model 

In [29]:
SVR_model = SVR( C = 20 , kernel= "rbf" , epsilon = 0.01 , max_iter=1000)
SVR_model.fit(X_train , y_train)
Model_Training_Score = SVR_model.score(X_train , y_train)
Model_Tesing_Score = SVR_model.score(X_test , y_test)
y_pred = SVR_model.predict(X_test)

MAE = mean_absolute_error(y_test , y_pred , multioutput="uniform_average")
MSE = mean_squared_error(y_test , y_pred , multioutput="uniform_average")
Mid_A_E = median_absolute_error(y_test , y_pred)
r2_score = np.sqrt(MSE)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


In [30]:
print(f"The Model_Training_Score :: {Model_Training_Score}\n=======\nThe Model_Tesing_Score ::\
{Model_Tesing_Score}\n=======\nThe y_pred :: \n{y_pred[:10]}\nthe y_real :: \n{y_test[:10]}\n=======\n\
The MAE :: {MAE}\n=====\nThe MSE :: {MSE}\n======\nthe Mid_A_E :: {Mid_A_E}\n======\nThe r2 Score ::\
{r2_score}")

The Model_Training_Score :: 0.9527451268798963
The Model_Tesing_Score ::0.7660492911076839
The y_pred :: 
[ 0.09726297 -1.96359555 -0.46198457 -1.88417115  0.39956333 -2.05963296
  0.14219715  0.60257903 -2.00600904  0.06567478]
the y_real :: 
[ 0.24073852 -0.97258364  0.55530353 -2.09603009  0.24073852 -1.80393401
  0.5328346   0.46542781 -2.16343687 -0.11876434]
The MAE :: 0.3832224569297728
=====
The MSE :: 0.2632909402674465
the Mid_A_E :: 0.2556989454839611
The r2 Score ::0.5131188363989831


* Changing the SVR_Model_hyperparameter values

In [27]:
SVR_model = SVR( C = 20 , kernel= "linear" , epsilon = 0.01 , max_iter=1000)
SVR_model.fit(X_train , y_train)
Model_Training_Score = SVR_model.score(X_train , y_train)
Model_Tesing_Score = SVR_model.score(X_test , y_test)
y_pred = SVR_model.predict(X_test)

MAE = mean_absolute_error(y_test , y_pred , multioutput="uniform_average")
MSE = mean_squared_error(y_test , y_pred , multioutput="uniform_average")
Mid_A_E = median_absolute_error(y_test , y_pred)
r2_score = np.sqrt(MSE)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


In [28]:
print(f"The Model_Training_Score :: {Model_Training_Score}\n=======\nThe Model_Tesing_Score ::\
{Model_Tesing_Score}\n=======\nThe y_pred :: \n{y_pred[:10]}\nthe y_real :: \n{y_test[:10]}\n=======\n\
The MAE :: {MAE}\n=====\nThe MSE :: {MSE}\n======\nthe Mid_A_E :: {Mid_A_E}\n======\nThe r2 Score ::\
{r2_score}")

The Model_Training_Score :: 0.8734150915782389
The Model_Tesing_Score ::0.9063576153697076
The y_pred :: 
[ 0.20368093 -1.78641012  0.74361564 -1.94300019  0.04919633 -1.58936596
  0.25128106  0.5612704  -1.90606684 -0.2700074 ]
the y_real :: 
[ 0.24073852 -0.97258364  0.55530353 -2.09603009  0.24073852 -1.80393401
  0.5328346   0.46542781 -2.16343687 -0.11876434]
The MAE :: 0.26060144092386384
=====
The MSE :: 0.10538626540150357
the Mid_A_E :: 0.23570977610147992
The r2 Score ::0.3246325082327763
