 # Function Transformer

    Execute CustoM Function On data

In [ ]:
#Import Libraries
from sklearn.preprocessing import FunctionTransformer
#----------------------------------------------------

#Function Transforming Data
'''
FunctionTransformer(func=None, inverse_func=None, validate= None,
                    accept_sparse=False,pass_y='deprecated', check_inverse=True,
                    kw_args=None,inv_kw_args=None)
'''

scaler = FunctionTransformer(func = lambda x: x**2,validate = True) # or func = function1
X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , y[:10])

In [1]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

data = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

# create function

def func1 (z) :
    return np.sqrt(z)

Rescalling_data = FunctionTransformer( func = func1 , validate = True )

New_data = Rescalling_data.fit_transform(data)

print(f"The orignal data ::\n\n{data}\n\n====\n\nThe New_data ::\n\n{New_data}")

The orignal data ::

[[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

====

The New_data ::

[[2.         1.         1.41421356 1.41421356]
 [1.         1.73205081 3.         1.73205081]
 [2.23606798 2.64575131 2.23606798 1.        ]]


In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

data = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

# Create Function Using Lambda

Rescalling_data = FunctionTransformer( func = lambda z : np.sqrt(z)  , validate = True ) 

New_data = Rescalling_data.fit_transform(data)

print(f"The orignal data ::\n\n{data}\n\n====\n\nThe New_data ::\n\n{New_data}")

The orignal data ::

[[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

====

The New_data ::

[[2.         1.         1.41421356 1.41421356]
 [1.         1.73205081 3.         1.73205081]
 [2.23606798 2.64575131 2.23606798 1.        ]]
