# Polynomial Features

    that technice increase The data Features to solve underfittig problem 

In [ ]:
#Import Libraries
from sklearn.preprocessing import PolynomialFeatures
#----------------------------------------------------

#Polynomial the Data

scaler = PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)
X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , y[:10])

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

data = np.arange(6).reshape(3,2)


# Baise if True insert ones colum  else not insert

# Interaction if True insert all polynomials such x**2 , x**3  else not insert them

Featurize = PolynomialFeatures( degree = 2 , include_bias = True , interaction_only = False)

New_Feature = Featurize.fit_transform(data)

print(f"The orignal Features ::\n\n{data}\n\n====\n\nThe New_Features ::\n\n{New_Feature}")


The orignal Features ::

[[0 1]
 [2 3]
 [4 5]]

====

The New_Features ::

[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [5]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

data = np.arange(6).reshape(3,2)


# Baise if True insert ones colum  else not insert

# Interaction if True insert all polynomials such x**2 , x**3  else not insert them

Featurize = PolynomialFeatures( degree = 2 , include_bias = False , interaction_only = True)

New_Feature = Featurize.fit_transform(data)

print(f"The orignal Features ::\n\n{data}\n\n====\n\nThe New_Features ::\n\n{New_Feature}")


The orignal Features ::

[[0 1]
 [2 3]
 [4 5]]

====

The New_Features ::

[[ 0.  1.  0.]
 [ 2.  3.  6.]
 [ 4.  5. 20.]]


In [7]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

data = np.arange(6).reshape(3,2)


# Baise if True insert ones colum  else not insert

# Interaction if True insert all polynomials such x**2 , x**3  else not insert them

Featurize = PolynomialFeatures( degree = 5 , include_bias = True , interaction_only = True)

New_Feature = Featurize.fit_transform(data)

print(f"The orignal Features ::\n\n{data}\n\n====\n\nThe New_Features ::\n\n{New_Feature}")


The orignal Features ::

[[0 1]
 [2 3]
 [4 5]]

====

The New_Features ::

[[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]
