In [1]:
import tensorflow as tf

In [ ]:
tf.

* constant in tensorflow

In [3]:
# tf.constant(value , shape = (rows , cols) , dtype = tf.dtype )
x1 = tf.constant(5)
x2 = tf.constant(5 , tf.float64)
x3 = tf.constant([1,2,2])
x4 = tf.constant([[1,2,3] , [4,5,6]])
x5 = tf.constant([[[1,2,3] , [4,5,6] , [7,8,9]]])
x6 = tf.constant("I love Tasorflow")

L = [x1 , x2 , x3 , x4 , x5 , x6]
for l in L :
    print(f"The Constant ::\n{l}\n***************************")

The Constant ::
5
***************************
The Constant ::
5.0
***************************
The Constant ::
[1 2 2]
***************************
The Constant ::
[[1 2 3]
 [4 5 6]]
***************************
The Constant ::
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
***************************
The Constant ::
b'I love Tasorflow'
***************************


In [12]:
O_M = tf.ones((3,3)) 
Z_M = tf.zeros((3,3))
I_M = tf.eye(3)
R_M = tf.random.normal((3,3) , mean=0 , stddev=1)
U_M = tf.random.uniform((1 , 3) , maxval=1)
G_M = tf.range(0 , 100 , 10)
C_M = tf.cast(G_M , tf.float64)
L = [O_M , Z_M , I_M , R_M , U_M , G_M , C_M]
for l in L :
    print(f"The Constant ::\n{l}\n***************************")

The Constant ::
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
***************************
The Constant ::
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
***************************
The Constant ::
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
***************************
The Constant ::
[[-1.030036   -0.03330532 -0.6307858 ]
 [-0.24579556  1.38935    -1.062898  ]
 [ 0.70307875 -0.09985785 -0.29867536]]
***************************
The Constant ::
[[0.5841148  0.99820995 0.00468755]]
***************************
The Constant ::
[ 0 10 20 30 40 50 60 70 80 90]
***************************
The Constant ::
[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
***************************


* Mathimatical_operations

In [21]:
x = tf.constant([[1,2,3]])
y = tf.constant([[4,5,6]])
w = tf.constant([[1,2,3] , [3,4,5]])
z = tf.constant([[1,2] ,[2,1],[2,2]])
add  = tf.add(x,y)  # x+y
sub  = tf.subtract(x,y)  # x-y
div  = tf.divide(x,y)  # x/y
mult = tf.multiply(x,y)  # x*y
T_dot = tf.tensordot(w,z , axes=1)
R_S   = tf.reduce_sum(x*y , axis=0) 
p_O = tf.pow(x , 3)  # x**3
M1 = tf.random.normal((2,3))
M2 = tf.random.normal((3,2))
Matul = tf.matmul(M1 , M2)  # M1 @ M2
O = [add , sub , div , mult , T_dot , R_S , p_O , Matul]
for o in O :
    print(f"The result ::\n {o}\n**************************")

The result ::
 [[5 7 9]]
**************************
The result ::
 [[-3 -3 -3]]
**************************
The result ::
 [[0.25 0.4  0.5 ]]
**************************
The result ::
 [[ 4 10 18]]
**************************
The result ::
 [[11 10]
 [21 20]]
**************************
The result ::
 [ 4 10 18]
**************************
The result ::
 [[ 1  8 27]]
**************************
The result ::
 [[-0.19567782  0.25243938]
 [-0.56481826  1.5484542 ]]
**************************


* Indexing

In [23]:
M = tf.range(0 , 100 , 10)
print(M[:])
print(M[:3])
print(M[2:])
print(M[::2])
print(M[::-1])

tf.Tensor([ 0 10 20 30 40 50 60 70 80 90], shape=(10,), dtype=int32)
tf.Tensor([ 0 10 20], shape=(3,), dtype=int32)
tf.Tensor([20 30 40 50 60 70 80 90], shape=(8,), dtype=int32)
tf.Tensor([ 0 20 40 60 80], shape=(5,), dtype=int32)
tf.Tensor([90 80 70 60 50 40 30 20 10  0], shape=(10,), dtype=int32)


In [33]:
indices = tf.constant([1,3])
M_idx  = tf.gather(M , indices)
M_idex = tf.gather(M , indices=[1 , 3])
print(M_idx ,"\n",M_idex)

tf.Tensor([10 30], shape=(2,), dtype=int32) 
 tf.Tensor([10 30], shape=(2,), dtype=int32)


In [34]:
Mx = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(Mx[: , 2])
print(Mx[1: , -1])

tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([6 9], shape=(2,), dtype=int32)


* Reshapping

In [36]:
M = tf.range(9)
print(M)
M = tf.reshape(M , (3,3))
print(M)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


* Transpose

In [39]:
M = tf.transpose(M , perm=[1,0])
print(M)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
