In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [5]:
(x_train , y_train) , (x_test , y_test) = mnist.load_data()

In [9]:
x_train = x_train.reshape(-1 , 28*28).astype("float32")/255.0
x_test  = x_test.reshape(-1 , 28*28).astype("float32")/255.0

In [10]:
print(x_train.shape)
print(y_test.shape)

(60000, 784)
(10000,)


In [11]:
import  numpy as np
m = np.arange(25).reshape(5,5)
print(m)
e = np.exp(m)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
  1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07
  1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
  2.64891221e+10]]
